import { RouteInfo } from '../../layout/sidebar/sidebar.metadata';
import { UserRole } from '../common-utils/classes/user-role';
export const MunicipalityManagerRoute: RouteInfo[] =[

  {
    path: '',
    title: 'Manage Schools',
    moduleName: 'micipalitymanager',
    iconType: 'material-icons-two-tone',
    icon: 'school',
    class: 'menu-toggle',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [UserRole[UserRole.MuncipalityManager]],
    submenu: [],
  },
  { 
        path: '/workspace/municipality-manager/allSchools',
        title: 'Show Schools',
        moduleName: 'micipalitymanager',
        iconType: 'material-icons-two-tone',
        icon: 'school',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [UserRole[UserRole.MuncipalityManager]],
        submenu: [],
  },
  {
    path: '/workspace/school-staff/attach',
    title: 'Attach Students',
    moduleName: 'schoolstaff',
    iconType: 'material-icons-two-tone',
    icon: 'person',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [UserRole[UserRole.MuncipalityManager]],
    submenu: [],
  },
  {   
    path: '/workspace/program-manager/allPrograms',
    title: 'Show Programs',
    moduleName: 'program-manager',
    iconType: 'material-icons-two-tone',
    icon: 'school',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [UserRole[UserRole.MuncipalityManager]],
    submenu: [],
},
{
  path: '/workspace/school/linkProgramsSchool',
  title: 'Link program to schools',
  moduleName: 'school',
  iconType: 'material-icons-two-tone',
  icon: 'layers',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: [UserRole[UserRole.MuncipalityManager]],
  submenu: [],
},
]