import { RouteInfo } from '../../layout/sidebar/sidebar.metadata';
import { UserRole } from '../common-utils/classes/user-role';
export const programManagerRoute: RouteInfo[] =[

  {
    path: '',
    title: 'Programs',
    moduleName: 'programmanager',
    iconType: 'material-icons-two-tone',
    icon: 'school',
    class: 'menu-toggle',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [UserRole[UserRole.ProgramManager]],
    submenu: [],
  },
  {   
    path: '/workspace/program-manager/allPrograms',
    title: 'Show Programs',
    moduleName: 'program-manager',
    iconType: 'material-icons-two-tone',
    icon: 'school',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [UserRole[UserRole.ProgramManager]],
    submenu: [],
},
{
  path: '/workspace/school-staff/attach',
  title: 'Attach Students to all schools',
  moduleName: 'schoolstaff',
  iconType: 'material-icons-two-tone',
  icon: 'person',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: [UserRole[UserRole.ProgramManager]],
  submenu: [],
},
{
  path: '/workspace/school/all',
  title: 'Show Programs to all schools',
  moduleName: 'school',
  iconType: 'material-icons-two-tone',
  icon: 'layers',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: [UserRole[UserRole.ProgramManager]],
  submenu: [],
},
{
  path: '/workspace/school/linkProgramsSchool',
  title: 'Link program to schools',
  moduleName: 'school',
  iconType: 'material-icons-two-tone',
  icon: 'layers',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: [UserRole[UserRole.ProgramManager]],
  submenu: [],
},
]